edit

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -24,11 +24,44 @@ jobs:
           exit 1
         fi
         docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
-    - name: Build Docker Compose services
-      run: docker compose -f docker-compose.yml build
-    - name: List Docker images
-      run: docker images
-    - name: Tag Docker image
-      run: docker tag advanced_pos_app:latest ${{ secrets.DOCKER_USERNAME }}/advanced_pos_app:latest
+    # - name: Build Docker Compose services
+    #   run: docker compose -f docker-compose.yml build
+    # - name: List Docker images
+    #   run: docker images
+    # - name: Tag Docker image
+    #   run: docker tag advanced_pos_app:latest ${{ secrets.DOCKER_USERNAME }}/advanced_pos_app:latest
+    - name: Build Docker Image
+      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/advanced_pos_app:latest .
     - name: Push Docker image to Docker Hub
       run: docker push ${{ secrets.DOCKER_USERNAME }}/advanced_pos_app:latest
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v2
+    - name: Login to Docker Hub
+      env:
+        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+      run: |
+        if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
+          echo "❌ Docker credentials are missing!"
+          exit 1
+        fi
+        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
+    - name: Pull Docker image from Docker Hub
+      run: docker pull ${{ secrets.DOCKER_USERNAME }}/advanced_pos_app:latest
+    - name: Stop and remove existing Docker container
+      run: |
+        if [ "$(docker ps -q -f name=advanced_pos_app)" ]; then
+          docker stop advanced_pos_app
+          docker rm advanced_pos_app
+        fi
+    - name: Run Docker container
+      run: docker run -d -p 8000:8000 --name advanced_pos_app ${{ secrets.DOCKER_USERNAME }}/advanced_pos_app:latest
+    - name: List Docker containers
+      run: docker ps
